= iotivity clojure sdk: minimal example

FIXME: description

== Usage

Set the environment variables IOTIVITY_HOME and IOTIVITY_LIBPATH.  You
can use `examples/source.me` to do this; edit it then do `$ source
source.me`.

Build the project

[source,sh]
----
$ mvn package
----

Run it:

[source,sd]
----
$ ./boot.sh cider repl
----

NOTE: This assumes you're using Emacs; for it to work you need to put
the following in `~/.boot/profile.boot`:

[source,clojure]
----
(deftask cider "CIDER profile"
  []
  (require 'boot.repl)
  (swap! @(resolve 'boot.repl/*default-dependencies*)
         concat '[[cider/cider-nrepl "0.12.0"]
                  #_[refactor-nrepl "2.0.0-SNAPSHOT"]])
  (swap! @(resolve 'boot.repl/*default-middleware*)
         concat '[cider.nrepl/cider-middleware
                  #_refactor-nrepl.middleware/wrap-refactor])
  identity)
----

If you're using some other nREPL-enabled editor you will of course
need to configure it appropriately.

WARNING:  You *must* use `boot.sh` or some equivalent method to set the `java.library.path`.


== troubleshooting

If you get link errors like

```java.lang.UnsatisfiedLinkError: no iotivity-jni in java.library.path```

Double check your paths.  You can print the effective java.library.path in the nREPL like so:

[source,clojure]
----
(println (System/getProperty "java.library.path"))
----

=== Options

FIXME: listing of options this app accepts.

## Examples

...

### Bugs

...

### Any Other Sections
### That You Think
### Might be Useful

## License

Copyright © 2016 FIXME

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
